### ISSUE TITLE
Windows Patches and Offline Updates

### ISSUE THREAD

**Issue by elyesusa** [FriendsOfMDT/PSD#101]
Greetings all,

I am trying to inject Patches and Windows updates into my deployment, so I can reduce the time of updates that run after. In my old regular MDT, I was able to do so by just adding packages and injecting them during deployment and worked for years with no issue, but for some reason with PSD MDT, it hasn't been working at all. So is there a different way to do or maybe you could integrate the WSUS server with PSD MDT or is there already a way to use WSUS with PSD?

**Comment by 3pichaxz0r** [comment]
This is more of a work around since its not part of PSD but you can do offline slipstreaming of your OS wims. What I do is mount the wim image I want to update using dism and then use the OSD powershell module to easily update the image, ex: 
```
dism /mount-image /imagefile:"E:\ISOs\Windows 11 Pro 22H2\install.wim" /index:1 /Mountdir:E:\mount
update-windowsImageOSD -Path "E:\mount" -Update All
dism /unmount-Image /MountDir:E:\Mount /commit
```
Then I remove the old image files from the deployment share using the mdt workbench and import the newly modified wims.

**Comment by elyesusa** [comment]
Thank you for your reply, I did try you work around but here is the error I have got:

 update-windowsImageOSD : The term 'update-windowsImageOSD' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ update-windowsImageOSD -Path "F:\mount" -Update All
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (update-windowsImageOSD:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by 3pichaxz0r** [comment]
Like I said its part of the OSD powershell module so you would need to install that first.
https://www.powershellgallery.com/packages/OSD

**Comment by elyesusa** [comment]
Thank you, that helped a lot
