### ISSUE TITLE
Trying to setup an SLShare folder and receiving an error running Set-PSDLogInstance.ps1

### ISSUE THREAD

**Issue by lmcadams2** [FriendsOfMDT/PSD#104]
I'm using the syntax .\Set-PSDLogInstance.ps1 -psDeploymentFolder E:\PSDProductionLogs -psVirtualDirectory PSDProductionLogs

But I'm receiving an error 'A parameter cannot be found that matches psDeploymentfolder'.  When I look at the powershell script, the input is looking for  '-PSvirtualDirectory' and a different file name is referenced? 

Hopefully this is why my SLShare logs aren't working.

Thank you!

**Comment by GeoSimos** [comment]
Hi @lmcadams2,

Have you setup the IIS part first? We have scripts for that and proper documentation in here and the downloaded solution.

**Comment by lmcadams2** [comment]
Hello @GeoSimos ,

I did setup the IIS for both virtual directories (PSDProductionLogs and PSDProduction) and I have enabled Bits upload, but I still get the same error message.

**Comment by GeoSimos** [comment]
> Hello @GeoSimos ,
> 
> I did setup the IIS for both virtual directories (PSDProductionLogs and PSDProduction) and I have enabled Bits upload, but I still get the same error message.

Please check my reply above and better start new by deleting the PSDProductionLogs Virtual directory.

**Comment by lmcadams2** [comment]
Thanks @GeoSimos!   That change worked for me and thank you for the instructions to interactively see the parameters and help.
