### ISSUE TITLE
i need a create a step to pause the task sequence in this PSD module

### ISSUE THREAD

**Issue by kraouf** [FriendsOfMDT/PSD#109]
i need to create a step to pause the task sequence in this PSD module and another thing does vbs scripts work in this module

**Comment by GeoSimos** [comment]
We don't block the running of VBS scripts, although the whole premise of the solution is to move away from them and embrace PowerShell.
You can create a pause script and add it wherever you want in the task sequence, here is a nice solution that applies to PSD/MDT as well [Pause a build task sequence using PowerShell in SCCM 2012 SP17](https://bit.ly/3QYQrkp).

**Comment by GeoSimos** [comment]
> thank you soo much , i will try that , great job by the way

Shall I close this issue?

**Comment by kraouf** [comment]
sure sorry for he delaying
