### ISSUE TITLE
Unable to set the keyboardlocale for winPE

### ISSUE THREAD

**Issue by pookkii** [FriendsOfMDT/PSD#110]
In the standard MDT, there was an option to set the keyboard locale in CustomSettings.ini by using the KeyboardLocalePE=0813:00000813 key. However, this no longer seems to work, and the PE environment defaults to QWERTY.

**Comment by pookkii** [comment]
Hi George,

You are correct , i forgot to mention it is also added to the bootstrap.ini. the image has been regenerated after it was added. I believe the "old" MDT uses the command wpeutil setkeyboardlayout 0803:00000813 to modify the keyboard locale for the winpe environment before starting the scripts , but i'm not sure. Perhaps there is an issue there ?

**Comment by GeoSimos** [comment]
> Hi George,
> 
> You are correct , i forgot to mention it is also added to the bootstrap.ini. the image has been regenerated after it was added. I believe the "old" MDT uses the command wpeutil setkeyboardlayout 0803:00000813 to modify the keyboard locale for the winpe environment before starting the scripts , but i'm not sure. Perhaps there is an issue there ? I also saw that the variable KeyboardlocalePE does get assigned on startup but for some reason it stays qwerty. Will check the logs again tomorrow to be sure.

The creation of the WinPE boot image is not affected by our code AFAIK -it does but not in a weird way-, however, if it doesn't work for you, I can relay it to the rest of the team and check it further.
Can you also mention your ADK and MDT versions please?

**Comment by pookkii** [comment]
> > Hi George,
> > You are correct , i forgot to mention it is also added to the bootstrap.ini. the image has been regenerated after it was added. I believe the "old" MDT uses the command wpeutil setkeyboardlayout 0803:00000813 to modify the keyboard locale for the winpe environment before starting the scripts , but i'm not sure. Perhaps there is an issue there ? I also saw that the variable KeyboardlocalePE does get assigned on startup but for some reason it stays qwerty. Will check the logs again tomorrow to be sure.
> 
> The creation of the WinPE boot image is not affected by our code AFAIK -it does but not in a weird way-, however, if it doesn't work for you, I can relay it to the rest of the team and check it further. Can you also mention your ADK and MDT versions please?

MDT version : 8456
ADK version : 10.1.25398.1

**Comment by pookkii** [comment]
For anyone having the same issue , i used this workaround to manually inject the keyboardlocale into the WinPE environment.

## Requirements

- Windows Assessment and Deployment Kit (ADK) installed.
- Administrative privileges on the system.
- Source WIM file (`LiteTouchPE_x64.wim`).

## Process

### Step 1: Verify or Create WinPE Working Directory

1. **Check WindowsPE Directory**:
   - Verify if `E:\WindowsPE` directory exists and contains files. 
   - If the directory does not exist or is empty, proceed to Step 2.

### Step 2: Run `copype` to Create WinPE Structure

2. **Execute copype in Deployment and Imaging Tools Environment**:
   - Run the following command in Deployment and Imaging Tools Environment to create a standard WinPE structure in `E:\WindowsPE`:
     ```
     copype amd64 E:\WindowsPE
     ```
   - This step is skipped if `E:\WindowsPE` already exists and contains files.

### Step 3: Mount the WIM File

3. **Mount LiteTouchPE_x64.wim**:
   - Mount the WIM file to a mount directory (`E:\windowsPE\mount`) using the following command:
     ```
     dism /mount-image /imagefile:"E:\PSD\Boot\LiteTouchPE_x64.wim" /index:1 /mountdir:"E:\windowsPE\mount"
     ```

### Step 4: Modify Keyboard Layout

4. **Check Current Keyboard Layout**:
   - Optionally, check the current keyboard settings with:
     ```
     dism /image:"E:\windowsPE\mount" /get-intl
     ```

5. **Set AZERTY Keyboard Layout**:
   - Change the input locale to Belgian AZERTY using (change this to the layout you want):
     ```
     dism /image:"E:\windowsPE\mount" /set-inputlocale:0813:00000813
     ```

### Step 5: Unmount and Commit Changes

6. **Unmount WIM File**:
   - Unmount the WIM and commit changes:
     ```
     dism /unmount-image /mountdir:"E:\windowsPE\mount" /commit
     ```

### Step 6: Prepare for ISO Creation

7. **Copy Modified WIM to Sources Folder**:
   - Copy the modified WIM file to the `Sources` folder in `E:\WindowsPE`:
     ```
     copy "E:\PSD\Boot\LiteTouchPE_x64.wim" E:\WindowsPE\media\sources\boot.wim
     ```

### Step 7: Create ISO File

8. **Generate ISO File**:
   - Create an ISO file from the `E:\windowsPE` directory using Deployment and Imaging Tools Environment:
     ```
     makewinpemedia /iso E:\windowsPE E:\Iso\LiteTouchPE_AZ_x64.iso
     ```

**Comment by pookkii** [comment]
Ah thanks for the info , didn't know that !

**Comment by GeoSimos** [comment]
@pookkii  and @3pichaxz0r  your posts are going to be integrated in the documentation, thank you for your contribution.
