### ISSUE TITLE
How to implement Final Configuration for MDT

### ISSUE THREAD

**Issue by JerichoJones** [FriendsOfMDT/PSD#120]
I have some processes that I want to run upon completion of the Task Sequence. PSDFinal.ps1 looks like an implementation of Final Configuration for MDT but I do not want to edit this file and I'm not certain this would do what I need.

How can I implement a Final Configuration for MDT like process after TS completion without poking the registry and rebooting?

**Comment by GeoSimos** [comment]
Well you are quite spot on, PSDFinal.ps1 is a form of the final configuration script which was doing the post deployment cleanup.
What I would do, is to create PowerShell script and call it in the PSDFinal.ps1, that way you keep the latter clean and you have your cleanup scripts separate (and as modular as you want).

**Comment by JerichoJones** [comment]
I ended up moving the folder deletion code into my my script and calling that script from PSDFinal.

**Comment by GeoSimos** [comment]
There is also another trick, you can use the setupcomplete.cmd script alternatively: [Add a Custom Script to Windows Setup](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-a-custom-script-to-windows-setup?view=windows-10). It works on all Windows type of OSs (Client/Server).

**Comment by JerichoJones** [comment]
I believe that I would have to modify the WIMs. I create them pretty regularly so this would be cumbersome.

**Comment by PowerShellCrack** [comment]
You could add a step into the task sequence that copies _setupcomplete.cmd_ to the OS drive (one OS is extracted), but that step runs after OS prepares itself not after the task sequence completes. 

What is the need to run it **after** the PSDFinal.ps1? Why not add a PowerShell step in the Task Sequence to run a script under the _custom task_ group?  You can always change the _FinalAction_ to not reboot.

**Comment by JerichoJones** [comment]
Because it invokes an application to join the domain and then the app reboots the machine.

**Comment by PowerShellCrack** [comment]
I guess I don't fully understand. The script you want to run as final will be an application that will join the domain? What's the reason for not use PSD domain join process? Are you trying to prevent a reboot during domain join?

**Comment by JerichoJones** [comment]
The application allows the user to browse Active Directory containers and pick the appropriate one. It also enforces our naming convention.

**Comment by GeoSimos** [comment]
> I believe that I would have to modify the WIMs. I create them pretty regularly so this would be cumbersome.

You can copy the setupcomplete.cmd file before the task sequence completes. No wim modification required.

**Comment by GeoSimos** [comment]
> The application allows the user to browse Active Directory containers and pick the appropriate one. It also enforces our naming convention.

But this should run in the beginning to be honest, because you want the name of the device to be correct and join the domain. The OU placement can happen later via your script.

**Comment by JerichoJones** [comment]
The process/application in question is a legacy one, originally developed
by an individual who is no longer available to support it. Additionally, it
utilizes a programming language with which I am no longer familiar, making
any updates quite challenging. Our environment is extensive, comprising
numerous sites each with their own organizational units, and we engage
student workers in our operations. While implementing changes at the outset
would indeed be beneficial, it necessitates further programming efforts. I
have already invested significant effort into adapting PSD to meet our
specific needs. In the future, I plan to revisit and possibly revamp this
process, but currently, my schedule does not permit this. Furthermore,
there's the task of preparing comprehensive documentation for both
technicians and student workers, which requires additional time investment.

**Comment by PowerShellCrack** [comment]
> The application allows the user to browse Active Directory containers and pick the appropriate one. It also enforces our naming convention.

You could use the new DomainOus process with the next release. This will allow multiple ou selection for device. 

I have also worked extensively on device naming with PowerShell. (Eg https://github.com/PowerShellCrack/OSDOOBEUI); I could look into developing a process to ensure device name meets compliance in the PSD Wizard when regex specified. Currently it only supports serial number (%SERIAL%) and random (%RAND%). However it will process names in properties as well, meaning if u specify a property in customsettings 
.ini like Prefix=DEV, and then you put %Prefix%-%Random:4% as the OSDComputerName, it would generate a name like "DEV-ef21"

**Comment by JerichoJones** [comment]
Although this is great add I don't think it will work for our environment. We restrict the naming through dropdown choices utilizing two fields. In the third field they fill in a number. We also do a check against AD to verify the name does not exist and then give further choices as to how to proceed. It also writes that (and more data) into the registry for auditing when we run into an oopsie.
The reason this was created was to avoid giving their account the ability to create/delete computer objects as this has created problems in the past.

**Comment by JerichoJones** [comment]
Sorry for being a bit redundant. ;)

**Comment by PowerShellCrack** [comment]
I can see that being more complicated but not impossible. IMO, this could be done using AD ADSI searcher within WinPE (No AD module needed) and a custom page added in PSDWizard (https://github.com/FriendsOfMDT/PSD/blob/master/Documentation/PowerShell%20Deployment%20-%20PSD%20Wizard%20Guide.md#custom-pages) but like you said, it requires some rework you may not have time for.

**Comment by JerichoJones** [comment]
That's a great idea but I cannot have an ID/pword easily readable on the server. The is a security constraint. I have an idea of how that might be done but not sure if it would work.

1. The logged in user (WinPE) would pick the OU from a Treeview.
2. Then name would be chosen via dropdowns
3. This would be passed to an internal webserver with their creds or a auth token
4. The webserver code would pre-create the object in AD
5. The join would be done with the logged on users acct

I'm not sure how we would handle step 5 to keep it secure. We wouldn't want them to be able to join outside this process.

**Comment by PowerShellCrack** [comment]
It took me about 10 minutes to build this page (only because I'm familiar with Visual Studio) and I've attempted to put some logic behind it with PowerShell additions in the PSDWizard.Helper.ps1 file to process it,   

This is just a sample of what have so far. 
![image](https://github.com/FriendsOfMDT/PSD/assets/20599825/b4b6e222-894b-481d-a5d5-9b54e0ae3f0c)

I did have to exposed more of the functions for the PSDWizardNew module for this to work; so that may not be release until next one. However it does need more work though to fix a looping issue whenever it triggers a dropdown event handler. 

The great thing is this was on my todo list to make custom pages more controllable; your just pushing me to get it done. lol

**Comment by PowerShellCrack** [comment]
> That's a great idea but I cannot have an ID/pword easily readable on the server. The is a security constraint. I have an idea of how that might be done but not sure if it would work.
> 
> 1. The logged in user (WinPE) would pick the OU from a Treeview.
> 2. The name would be chosen via dropdowns
> 3. This would be passed to an internal webserver with their creds or a auth token
> 4. The webserver code would pre-create the object in AD
> 5. The join would be done with the logged on users acct
> 
> I'm not sure how we would handle step 5 to keep it secure. We wouldn't want them to be able to join outside this process.



You can easily obfuscate the password in the PowerShell script or even add a AES key and hashed password to the customsetting.ini and let the PowerShell decrypted it when needed. 

I'd be curious how you "invent" steps 3 and 4; I have been looking into use the PowerShell Web Access, thinking that would be a viable option to trigger Offline domain joins, but no success.

Step 5 can be done using ODJ....**just like Autopilot does**. So, if step 4 sends the request for djoin command, then the response is a blob, that can be sent back to the device and it will join the domain.
