### ISSUE TITLE
Task Sequence Failed, Return Code -2147467259

### ISSUE THREAD

**Issue by ewrightmdy** [FriendsOfMDT/PSD#121]
Hi! I'm configuring PSD/MDT for the first time and I'm encountering the above error when the task sequence reaches the driver injection stage over PXE boot. I'm using the total control method as recommended, have already generated the driver package WIMs, and the task sequence I'm using is just the default PSD template with a factory Windows 11 image. If anyone has any recommendations on potential solutions or how to further troubleshoot this error, it would be much appreciated.

**Comment by ewrightmdy** [comment]
I managed to resolve the above issue by cleaning the disk beforehand with diskpart, however am now encountering a different error when it reaches the install OS phase: 'Unable to continue, could not access the WIM'.

**Comment by GeoSimos** [comment]
Any logs to share? Redacted for sensitive info please...

**Comment by ewrightmdy** [comment]
Here is the actual error message:

![20240115_104720](https://github.com/FriendsOfMDT/PSD/assets/150169590/b69590e1-22e8-45f9-bad2-6c43aa0a6164)

Here are the relevant portions of the smsts.log file: 

![Capture](https://github.com/FriendsOfMDT/PSD/assets/150169590/b5d6a56e-5442-4917-9d37-0feef3fc5c78)

The relevant portion of PSDStart.log:

![Capture1](https://github.com/FriendsOfMDT/PSD/assets/150169590/69999a55-b145-40f3-a63d-6d02fd128bbc)

Furthermore, after the failed task sequence, if I cd into the mounted S: drive, the specified 'MININT/Cache/Operating Systems' directory does not exist.

**Comment by GeoSimos** [comment]
If you could attach the files (check for any sensitive info and redact accordingly) it would be much more helpful to check it out.

**Comment by ewrightmdy** [comment]
[smsts.log](https://github.com/FriendsOfMDT/PSD/files/13953529/smsts.log)
[PSDStart.log](https://github.com/FriendsOfMDT/PSD/files/13953530/PSDStart.log)

**Comment by GeoSimos** [comment]
From what I see in the logs, you use UNC paths for the deployroot path, please read the documentation because you have to setup your environment for http/https deployment shares.
Can you confirm that this is the case? Because it is evident in the log files.

**Comment by GeoSimos** [comment]
Glad to hear that!
Please read the documentation, it will save you a lot of time and hair pulling :-)

**Comment by lyonelf** [comment]
Hi,

All right for UNC. 

But many scripts that work in UNC don't work in http.

Because powershell command are not compatible

For example powershell.exe -file XXXX    the -file parameter is not supported in http

So how can convert our installation software scripts ?
