### ISSUE TITLE
Logs not being generated

### ISSUE THREAD

**Issue by IT-Roman** [FriendsOfMDT/PSD#126]
I've ran the scripts and created a PSDLogs folder nested in my existing PDS share.
This has been added to CustomSettings:

LogUserDomain=domain.com
LogUserID=MDTAdmin
LogUserPassword=password
SLShare=https://mdt01.domain.com/win10psd/PSDLogs/

However, logs are not being generated by deployments.
I am able to navigate to the share in my browser, and I am able to image a computer from that share. I do have problems with installing applications, but getting logging o work will probably help with that.

**Comment by GeoSimos** [comment]
Hi @IT-Roman,

Have you checked the steps in the documentation? [Server Side logging via BITS Upload](https://github.com/FriendsOfMDT/PSD/blob/497e613f81ab5f363d3ae175a71b71544e38f9db/Documentation/PowerShell%20Deployment%20-%20IIS%20Configuration%20Guide.md#server-side-logging-via-bits-upload)

**Comment by arwidmark** [comment]
Logging seems to be working ok, but you need to specify a specific (single) virtual directory, like https://mdt01.corp.viamonstra.com/PSDProductionLogs, which source folder should be **outside** of the deployment share. It's a massive security risk of allowing uploads of file, to a share where the PSD installation account can execute a file. Logs should always be kept outside of the PSD website.
