### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by ewrightmdy** [FriendsOfMDT/PSD#128]
Hi,

We've been attempting to configure IIS for our PSD instance and we've been running into some configuration errors that we're at a loss on to how to resolve. We've gone through the Set-PSDWebInstance script line by line and verified that every setting is correct, yet we are still encountering the below error in IIS:

![image](https://github.com/FriendsOfMDT/PSD/assets/150169590/f641186b-c14e-47e8-9717-579a9b057d8f)

We've already verified that the IIS_IUSRS user has read access to the web.config files in both the C:/inetpub/wwwroot folder as well as the deployment share, which is Microsoft's recommended fix for that error code.

Our web.config file:

![Capture](https://github.com/FriendsOfMDT/PSD/assets/150169590/9130d708-a079-4e17-88b7-d42f2c3f4c9e)

We would prefer not to wipe our server and restart from scratch, so anyone could point us in the right direction as to where to troubleshoot next, it would be much appreciated. Thank you!

**Comment by GeoSimos** [comment]
Hello @ewrightmdy,

First of all, where did you created your deployment share? 
Does the path I see "E:\DeploymentShare" contains one deployment share or you have different ones underneath it?
Next, after you create a deployment share, you have to run the helper script "New-PSDWebInstance.ps1" and later the configuration script "Set-PSDWebInstance.ps1, after that, you have to run the scripts for the certificate creation and copying in the solution.
My understanding is that you have skipped reading the documentation for this part of the solution, please check it here [IIS Configuration Guide](https://github.com/FriendsOfMDT/PSD/blob/497e613f81ab5f363d3ae175a71b71544e38f9db/Documentation/PowerShell%20Deployment%20-%20IIS%20Configuration%20Guide.md#install-iis-and-configure-webdav).
