### ISSUE TITLE
Command Prompt pop-up after "Checking for a valid network configuration"

### ISSUE THREAD

**Issue by dabigdragon** [FriendsOfMDT/PSD#145]
Hello,
I've followed the documentation to set up a brand new PSD share, and had IIS installed and configured via the scripts. I've loaded WinPE11 drivers and also run the "New PSD Drivers" script to import them as a ZIP file.

When booting the PE image via LiteTouch, it gets to "Checking for a valid network configuration" then throws up a command prompt window. It grabs a valid IP and I can ping our domain controllers and authenticate to the MDTPSD share through said command prompt window so the network is talking. It just seems that the PSDWizard isn't starting.

Am I missing a step somewhere within the setup?

**Comment by GeoSimos** [comment]
Hi @dabigdragon,

I saw that you closed this, issue, would you like to add some comments about it please?

**Comment by dabigdragon** [comment]
Hello!

With some assistance from a user on Reddit, I was able to figure out that my bootstrap.ini file was misconfigured.
The original issue is resolved but I now have the same issue as this post: https://github.com/FriendsOfMDT/PSD/issues/128

Working through that now.

**Comment by GeoSimos** [comment]
Did you used the bootstrap.ini file that comes with the solution or you copied one from your MDT deployment share? Also some more info regarding the contents of your bootstrap.ini or other files like customsettings.ini would be helpful for troubleshooting assistance when reporting an issue. 
It's not easy to guess what has been set on every setup.

**Comment by dabigdragon** [comment]
It's a fresh install as recommended by the documentation, so the one that came with the solution.

Fair enough, I'll provide more details about our setup in the future should I run into any further issues.
