### ISSUE TITLE
KeyboardLocale and TimeZone not getting set after defining Rules

### ISSUE THREAD

**Issue by Chopsticks143** [FriendsOfMDT/PSD#156]
Hi, I'm currently testing PSD and have run into this issue. 
Somehow PSD is not gathering all the rules. Only the domain is automatically put in to the Wizard. KeyboardLocale stays on us-US and Timezone has to be selected manually. The DomainOUList.xml is also not showing up in the Deployment phase. 
I fully updatet the Image and even replaced it on the WDS Server but there's still no change. 
I'd be happy if someone can help me

**Customsettings.ini**
[Settings]
Priority=Default
Properties=LogUserDomain,LogUserID,LogUserPassword,DriverPath,GenericDriverPath,FallBackDriverPath,PSDWizard,PSDWizardTheme

[Default]
OSInstall=Y
PSDWizard=PSDWizardNew
PSDWizardTheme=Classic
_SMSTSORGNAME=ViaMonstra
_SMSTSPackageName=PC soon to be in Service
;LogUserDomain=Server
;LogUserID=AccountName
;LogUserPassword=P@ssw0rd
SkipFinalSummary=NO
FinishAction=NONE
HideShell=YES
;AdminPassword=P@ssw0rd

JoinDomain=mydomain.local
TimeZoneName=W. Europe Standard Time
KeyboardLocale=0407:00000407
KeyboardLocalePE=0407:00000407
UILanguage=de-DE
UserLocale=de-DE
KeyboardLocale=de-DE

**Bootstrap.ini**

[Settings]
Priority=PSDRoots,Default
Properties=PSDDebug, PSDDeployRoots,PSDPrestartMode

[PSDRoots]
PSDDeployRoots=https://mdt01.domain.local/PSD Share
;UserDomain=MDT01
;UserID=MDT_BA
;UserPassword=P@ssw0rd
SkipBDDWelcome=YES

[Default]
PSDPrestartMode=Native
PSDDebug=NO
JoinDomain=mydomain.local
TimeZoneName=W. Europe Standard Time
KeyboardLocale=0407:00000407
KeyboardLocalePE=0407:00000407
UILanguage=de-DE
UserLocale=de-DE
KeyboardLocale=de-DE

**Comment by nicolux2006** [comment]
My Solution would be this:

Mount-WindowsImage -Path "C:\temp" -ImagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe.wim" -Index 1 -Verbose
Add-WindowsPackage -PackagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\WinPE_OCs\fr-FR\lp.cab" -Path "C:\temp" -Verbose
DISM /image:C:\Mount /set-UILang:de-DE
DISM /image:C:\Mount /Set-SysLocale:de-DE
DISM /image:C:\Mount /set-UserLocale:de-DE
DISM /image:C:\Mount /set-InputLocale:de-DE
Remove-WindowsPackage -Path "C:\temp" -PackageName Microsoft-Windows-WinPE-LanguagePack-Package~31bf3856ad364e35~amd64~en-US~10.0.25398.1
Start-Process "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\DISM\dism.exe" -ArgumentList " /Image:`"C:\temp`" /Cleanup-image /StartComponentCleanup /Resetbase /Defer" -Wait -LoadUserProfile
Start-Process "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\DISM\dism.exe" -ArgumentList " /Image:`"C:\temp`" /Cleanup-image /StartComponentCleanup /Resetbase" -Wait -LoadUserProfile`
Dismount-WindowsImage -Path "C:\temp" -Save -Verbose
Export-WindowsImage -SourceImagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe.wim" -SourceIndex 1 -DestinationImagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe-export.wim" -CompressionType max -Verbose
Remove-Item -Path "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe.wim" -Force

**Comment by Chopsticks143** [comment]
> My Solution would be this:
> 
> Mount-WindowsImage -Path "C:\temp" -ImagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe.wim" -Index 1 -Verbose Add-WindowsPackage -PackagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\WinPE_OCs\fr-FR\lp.cab" -Path "C:\temp" -Verbose DISM /image:C:\Mount /set-UILang:de-DE DISM /image:C:\Mount /Set-SysLocale:de-DE DISM /image:C:\Mount /set-UserLocale:de-DE DISM /image:C:\Mount /set-InputLocale:de-DE Remove-WindowsPackage -Path "C:\temp" -PackageName Microsoft-Windows-WinPE-LanguagePack-Package~31bf3856ad364e35~amd64~en-US~10.0.25398.1 Start-Process "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\DISM\dism.exe" -ArgumentList " /Image:"C:\temp" /Cleanup-image /StartComponentCleanup /Resetbase /Defer" -Wait -LoadUserProfile Start-Process "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\DISM\dism.exe" -ArgumentList " /Image:"C:\temp" /Cleanup-image /StartComponentCleanup /Resetbase" -Wait -LoadUserProfile` Dismount-WindowsImage -Path "C:\temp" -Save -Verbose Export-WindowsImage -SourceImagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe.wim" -SourceIndex 1 -DestinationImagePath "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe-export.wim" -CompressionType max -Verbose Remove-Item -Path "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe.wim" -Force

/

**Comment by Chopsticks143** [comment]
Well I found something where you mount your image into WinPE Environment and change the settings there. For the DomainOUList.xml theres no solution unfortunately.
But thanks for your help :)

**Comment by PowerShellCrack** [comment]
@Chopsticks143 We are working on a solution for the DomainOUList...

https://github.com/FriendsOfMDT/PSD/issues/135

**Comment by Chopsticks143** [comment]
@PowerShellCrack 

I Build a Dropdown menu into the PSDWizard_DeviceDetails_en-US.xaml for the Org Unit. 

<ComboBox x:Name="TS_JoinDomainOU" Grid.Column="1" Grid.RowSpan="2" HorizontalAlignment="Center" VerticalAlignment="Bottom" Margin="0,2,0,5" Width="295" Height="28" FontSize="14">
    <ComboBoxItem>OU=mit Verschluesselung,OU=Rechner,OU=Gessmann,DC=wgessmann,DC=local</ComboBoxItem>
    <ComboBoxItem>OU=ohne Verschluesselung,OU=Rechner,OU=Gessmann,DC=wgessmann,DC=local</ComboBoxItem>
</ComboBox>	

It seems to work, but everytime I choose the OU in the Dropdown Menu the Device Name gets reseted to MININT-XXXXX.
Are TS_OSDComputerName and TS_JoinDomainOU somehow connected?
I know this is not ideal but typing in the full OU path is not very elegant.

**Comment by PowerShellCrack** [comment]
No they are not connected. Most likely what is causing that is an event handler in the PowerShell code triggering something when drop down is selected. I’m not sure and would have to test that. But again there is a fix coming (in peer review right now) where you can specify the OUs in the CS.ini and it will auto generate a dropdown for you at the device details screen.
