### ISSUE TITLE
Right, Left, Mid functions in customsettings.ini sections

### ISSUE THREAD

**Issue by DocJelly** [FriendsOfMDT/PSD#167]
Do these "functions" still work in PSD? I've copied over a bunch of things from my MDT customsettings.ini to the PSD customsettings.ini and while I am able to get ByLaptop, ByDesktop etc. to create a %ComputerTypeName% variable, trying to get part of the asset tag or serial number fails.

```
[Settings]
Priority=Init,ByLaptop,ByDesktop,ByVirtual,Default
Properties=ComputerAssetNumber,ComputerTypeName,LogUserDomain,LogUserID,LogUserPassword,DriverPath,GenericDriverPath,FallBackDriverPath,PSDWizard,PSDWizardTheme,MyCustomProperty
[Init]
ComputerAssetNumber=#Right("%AssetTag%",4)#
[Default]
OSDComputerName=MyPrefix%ComputerAssetNumber%%ComputerTypeName%

```

I end up with an ComputerAssetNumber of `#Right("ABCDEFGH",4)#` and then my OSDComputerName is `MyPrefix#Right("ABCDEFGH",4)#LAP`

I also tried using some of the documented dynamic values in [PSD Wizard Guide](https://github.com/FriendsOfMDT/PSD/blob/master/Documentation/PowerShell%20Deployment%20-%20PSD%20Wizard%20Guide.md#supported-variables-in-customsettingini) like %SERIAL:4% and ended up with an OSDComputerName of "MyPrefix%SERIAL:4%LAP"  so it's not "resolving" those variables in my [init] section.

The end result is a hostname longer than 15 characters and a panther error after it reboots into the OS.

I've also noticed that %TaskSequenceName% doesn't resolve either. That's just cosmetic on the progress meter, but could be indicative of a larger problem of resolving variables in my customsettings.

**Comment by SBolt11** [comment]
I must admit I have just resorted to using   -%SERIAL%   as my value in cs.ini, and then deleting characters as required. I did post some questions on these variables too, I'm sure the team are working on incorparating more variables in the next release...I hope.

The variable does at least resolve for me. I hope that helps somewhat.

**Comment by DocJelly** [comment]
the %AssetNum% IS being resolved, but the #Left( )# or #Right( )# is not. here's a screenshot from the progress meter showing both errors:
![image](https://github.com/user-attachments/assets/c3e35f28-822a-487b-b759-b3b57889a907)
%TaskSequenceName% doesn't resolve to the name of the TS, and the %AssetTag% of this VM is the whole thing, not just the rightmost (or leftmost) 4 digits. The prefix is typed in the cs.ini and the suffix is being successfully determined and tacked on the end... just not trimming the asset tag correctly.
I've got some time yet, this is still just testing Win11 deployments, nothing in prod yet (despite the name of the org in the screenshot.) Hopefully there's an update before then and we don't have to do something drastic like manually renaming after imaging :)

**Comment by PowerShellCrack** [comment]
The _Right_, _Left_, and _Mid_ sub routines are native to VB and do not exist in PowerShell. However, the PSDWizard module incorporates the _%SERIAL%_ or _%SERIALNUMBER%_ using a custom function (Get-PSDWizardComputerName), so this can be theoretically achieved. The function should take <num> as a parameter representing the "length" to extract from the left or right and remove the rest accordingly. 

To investigate further, please enable PSDDebug and send the PSD.log. This log should reveal what the function is processing.

Another concern is that the wizard is the last module to load, so it relies on the TSEnv variables that have already been processed as key values. If the Init section isn't processed correctly, this could be causing the issue. I'll conduct some additional testing on this. In the meantime, I recommend avoiding the use of VB's _Right_, _Left_, and _Mid_ sub routines.

I will say some of the PSDWizard functions aren't working as intended and the next release will resolve these. However, it does not take into account the AssetTag...something I would need to add to my backlog.

**Comment by DocJelly** [comment]
Ahh, that would explain it.. I'm off this week but I will look in to the PSWizard module and see if I can use that or modify it to pull the asset tag, either from %AssetTag% or from WMI/CIMinstance itself with PowerShell.

**Comment by DocJelly** [comment]
I went into Tools\Modules\PSDGather and opened up PSDGather.psm1 and changed line 117 to extract just the last 4 chars of the %AssetTag% which is what we use for our OSDComputerName internally. Updated deployment share and booted a new VM, and it's OSDComputername now matches what we have in MDT and doesn't break the 15 character limit.
the new line 117 looks like this:
`$LocalInfo['AssetTag'] = $_.SMBIOSAssetTag.Trim().remove(0,$_.SMBIOSAssetTag.Length-4)`
It'll do for now...
