### ISSUE TITLE
After PSD Update, I'm not longer able to access the deploymentshare on lighttouch boot over network

### ISSUE THREAD

**Issue by technerdist** [FriendsOfMDT/PSD#190]
Hi,

After updating PSD, I can no longer launch Litetouch over PXE. It cannot validate access to the deploymentshare, and it appears that the variable for the deployment share path isn't populating. How can I troubleshoot this? If you look in the image below, it appears that Litetouch is trying to validate network access but there is no share shown. 

![image](https://github.com/user-attachments/assets/4f11398c-8987-44d8-a547-6412ae8328db)

**Comment by Audigy35** [comment]
https://github.com/FriendsOfMDT/PSD/issues/175

**Comment by technerdist** [comment]
The solution in issue #175 posted above fixed my problem. Thank you!
