### ISSUE TITLE
Error launching PSD Wizard since update

### ISSUE THREAD

**Issue by technerdist** [FriendsOfMDT/PSD#192]
Since I updated PSD to the latest version, I've been having an issue launching the readiness script. This breaks the wizard. I get the following error.

The term 'X:\MININT\Cache\PSDResources\Readiness\' is not recognized as the name of a cmdlet, function, scriptfile or operable program.

Any help would be greatly appreciated.

**Comment by PowerShellCrack** [comment]
PSD 2.30 has a lot of changes in it and requires some manual effort to updates. The Install-PSD.ps1 does not fix it all. I have created new documentation for it but it is in the CurrentDev under review. Follow this and see if it fixes your issue: https://github.com/FriendsOfMDT/PSD/blob/CurrentDev/Documentation/PowerShell%20Deployment%20-%20Latest%20Release%20Setup%20Guide.md#review-psd-install

**Comment by PowerShellCrack** [comment]
Did any of these steps solve your problem?

**Comment by technerdist** [comment]
Yes this is resolved. Thanks for your help.

**Comment by technerdist** [comment]
Closing issue
