### ISSUE TITLE
ADK and ADKPE Detection are working in en-Us OSCulture but not In other OsCulture

### ISSUE THREAD

**Issue by JM2K69** [FriendsOfMDT/PSD#23]
There is an error In ADK and ADKPE detection

https://github.com/FriendsOfMDT/PSD/blob/da134d186591e00693c17766bebf6ff655c61b35/Installer/Install-PSD.ps1#L51-L57

Here two functions works in FR-FR and en-US OsCulture

[ADK_ADKPE_detection.zip](https://github.com/FriendsOfMDT/PSD/files/3167369/ADK_ADKPE_detection.zip)

**Comment by JM2K69** [comment]
Here the Text on French OS Windows 10 1903 with ADKPE 1903 installed

![ADKPE](https://user-images.githubusercontent.com/17923944/57542750-ccae5380-7352-11e9-9b14-6a5e7d072691.PNG)

**Comment by soupman98** [comment]
Thanks @JM2K69. We'll make note of it for now. All of our initial prep and testing for 1.0 release at MMSMOS was based on EN/US dev and testing only. Thanks for the code snippet. @JordanTheITGuy take a look?

**Comment by JordanTheITGuy** [comment]
Noted - Will investigate a better way to check for ADK when in different language culture.

**Comment by JordanTheITGuy** [comment]
This should be no longer applicable closing.
