### ISSUE TITLE
File selection of ISO doesn't check for file extension

### ISSUE THREAD

**Issue by thenotoriousdrr** [FriendsOfMDT/PSD#25]
If you leave off the .ISO file extension in the hydration pack, the installer cannot find the file and throws errors but does not cause the script to fail.

**Comment by soupman98** [comment]
Great bug find. @JordanTheITGuy can you take a look and adjust the PSD Hydration script please.

**Comment by JordanTheITGuy** [comment]
This sill be fixed in the next version. Next version will also offer a "browse" button that will allow the user to use a GUI to select it.
