### ISSUE TITLE
Two missing files for ADK 1809 - Can they be added to Hydration kit?

### ISSUE THREAD

**Issue by thenotoriousdrr** [FriendsOfMDT/PSD#26]
While WinPE looks to see if the missing files from ADK 1809 are missing, would it be an easy fix to have those files auto added by the hydration kit if it detects ADK 1809? If not, could we get a URL to the file location to make the user's life a touch easier?

![image](https://user-images.githubusercontent.com/49260084/57594566-57837f80-7506-11e9-839e-3fdf648f1284.png)

**Comment by soupman98** [comment]
Hi Donna,
Due to legal restrictions and legalese... we can't provide binaries in MDT/PSD. You'll need to source those from your media sources. Sorry.

**Comment by thenotoriousdrr** [comment]
No worries! I totally get it.

Donna Ryan
Cell: 216-973-2468
Email: DonnaRoseRyan@outlook.com
Twitter: @TheNotoriousDRR

________________________________

**Comment by Hammarskjold** [comment]
Closing as MS fixed this as well.
