### ISSUE TITLE
UI Issue - Need error check to validate actual Task Sequence selection

### ISSUE THREAD

**Issue by thenotoriousdrr** [FriendsOfMDT/PSD#27]
The user is able to hit the OK button to start the imaging process on the TS Selection pane, even if the user hasn't selected a Task Sequence. This results in the process failing. The image attached shows the error

![image](https://user-images.githubusercontent.com/49260084/57634421-44f35f80-7573-11e9-8caa-915c67dbd80b.png)

**Comment by DeploymentBunny** [comment]
Known issue, should be documented as the first step, and fixed as a later step @soupman98, can U make sure the notes says this!

**Comment by GeoSimos** [comment]
Has been fixed in the new PSD Wizard.
