### ISSUE TITLE
MDT Monitoring Service failed to install

### ISSUE THREAD

**Issue by thenotoriousdrr** [FriendsOfMDT/PSD#28]
On a PSD instance created with the Hydration Kit, the MDT Monitoring Service failed to install. The checkbox under Deployment Share properties was selected. This caused the TS to fail.

Unchecking and rechecking the box created and started the service.

![image](https://user-images.githubusercontent.com/49260084/57636982-47a48380-7578-11e9-87f9-fe3bc655f079.png)

**Comment by DeploymentBunny** [comment]
Thank You, I'll make sure the @JordanTheITGuy fix this!

**Comment by JordanTheITGuy** [comment]
When you enable the MDT Monitoring service via the GUI it enables and creates the MDT_Monitoring service. However, when you do this via PowerShell there are two steps that are required creation of the service and then enabling the checkbox. Just setting the service to active for the share via powerShell does NOT create the service. Currently testing potential solution in Dev.

**Comment by JordanTheITGuy** [comment]
Fixed in Version 9.9 in dev.
