### ISSUE TITLE
Missing break; or bad documentation?

### ISSUE THREAD

**Issue by Raynefire14** [FriendsOfMDT/PSD#29]
https://github.com/FriendsOfMDT/PSD/blob/da134d186591e00693c17766bebf6ff655c61b35/Installer/New-PSDWebInstance.ps1#L687

The Write-PSDInstallLog -Message on line 688 of the New-PSDWebInstance.ps1 file refers to "now exiting" 

elsewhere this phrase precedes a break command, but here there is none. 

I don't know enough about what's going on to figure out if the log output is incorrect or if there is a missing break.

**Comment by soupman98** [comment]
@JordanTheITGuy can you please take a look?
Thanks @Raynefire14

**Comment by JordanTheITGuy** [comment]
This was a place holder install line for remote hydration in the future. This will be fixed in a later revision.

The Invoke-IISfunction needs to have parameter order specified still etc. I wanted to have the logic built to allow for remote hydration.
