### ISSUE TITLE
UI Issue - Double clicking on Task Sequence creates duplicate nested entries

### ISSUE THREAD

**Issue by brianfgonzalez** [FriendsOfMDT/PSD#36]
Double-clicking on a Task Sequence in the PSD Wizard, creates duplicate entries nested below the selected Task Sequence.

![image](https://user-images.githubusercontent.com/1973673/58741115-b17bb480-83e3-11e9-901a-4d4c19ee9b23.png)

**Comment by soupman98** [comment]
Thanks @brianfgonzalez. This is a known issue with tree and WPF (but didn't know it would just keep recursing). We've documented it for now. Assigning to DB for comment or investigation.

**Comment by Hammarskjold** [comment]
Unsure what the expanded view should show actually, so not 100% why it's a treeview to be honest. Will discuss with Johan and see if he knows.

**Comment by GeoSimos** [comment]
The old wizard has been deprecated and replaced by the new reworked one.
