### ISSUE TITLE
Cannot find path '.\Scripts\PSDWizard.psm1' 

### ISSUE THREAD

**Issue by GrantHarrington** [FriendsOfMDT/PSD#37]
Calling the Install-PSD.ps1 ."C:\Users\RS.Grant.Harrington\Scripts\Install-PSD.ps1" -psDeploymentFolder $PSDeployFolder -psDeploymentShare $PSDDS from Powershell CLI (not using ISE)

![image](https://user-images.githubusercontent.com/42081869/59558230-2853a880-8fb3-11e9-8b28-a879cfd0e046.png)

**Comment by arwidmark** [comment]
Solved: Dependency files were not downloaded prior to running the Install-PSD.ps1 script.  When installing the solution, make sure to download the entire repository. Will add clarification to the docs, and update the Install-PSD.ps1 to verify installation structure.
