### ISSUE TITLE
New-PSDDriverPackage creating large ZIP Files

### ISSUE THREAD

**Issue by JoriPS1** [FriendsOfMDT/PSD#48]
For specific behavior example, Dell Latitude 7420.  The driver pack CAB is 1.84GB, the extracted folder size is 3.42GB.

However, the file generated by New-PSDDriverPackage is 5.21GB and its source folder is over 9GB.

I think I've narrowed down the issue to..

Within New-PSDDriverPackage it takes the Driver name from MDT and iterates through each of them.  These drivers however can live in the same source folder, but have different classes.  The script itself looks at driver classes and creates a folder based off of the class.  It then copies the entire source folder to that folder.  This leads to redundant files in different folders.  If it's a small driver, it's fine.  But in the case of video drivers, this leads to multiple GB's difference between the uncompressed source, and the zip file.

Back to the example of the 7420, the video drivers are in Display, Extension, MEDIA and SoftwareComponent.

**Comment by arwidmark** [comment]
This issue has been resolved in the latest of the script, and the script now also support WIM format in addition to the ZIP format.
