### ISSUE TITLE
Small Regression in PSDUtility.psm1 (Copy-PSDFolder)

### ISSUE THREAD

**Issue by ASlowTurtle** [FriendsOfMDT/PSD#49]
Copy-PSDFolder in PSDUtility.psm1 returns the output of
```Powershell
& xcopy $s $d /s /e /v /d /y /i
```
The output breaks a check with Test-Path in PSDStart.ps1 (Line 563) causing the task sequence to fail

In the old version the output of this was piped to Out-Null. Changing the line back to
```Powershell
& xcopy $s $d /s /e /v /d /y /i | Out-Null
```
seems to fix the issue.

**Comment by GeoSimos** [comment]
This has been fixed more than a year ago (maybe two).
