### ISSUE TITLE
PSD Development Tools - MarkdownTOC Extension not available anymore - recommended alternatives?

### ISSUE THREAD

**Issue by mdwoernhard** [FriendsOfMDT/PSD#53]
The [CONTRIBUTING.md](https://github.com/FriendsOfMDT/PSD/blob/master/CONTRIBUTING.md) file lists the [MarkdownTOC Extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc). This extension is not available on the marketplace any longer. Are there any recommended alternatives?

**Comment by GeoSimos** [comment]
Visual Studio code has Markdown support out of the box for some time now https://code.visualstudio.com/docs/languages/markdown
also, you may want to check these nice posts:

-  https://www.makeuseof.com/vscode-ultimate-markdown-editor
- https://coderscat.com/awesome-vscode-extensions-for-markdown
