### ISSUE TITLE
HTTP deployment share is not setting

### ISSUE THREAD

**Issue by sarajune** [FriendsOfMDT/PSD#54]
After configuring the IIS as per the steps you mentioned.

The deployment share in the Listtouch iso is still trying to access the UNC path.

![image](https://user-images.githubusercontent.com/92084078/137585188-2f8e0489-d85a-44a5-9449-97f48dc3245c.png)

Because of which, the internet deployment is not working

Please suggest how to fix this?

**Comment by GeoSimos** [comment]
Hello, you have to set it also in the Bootstrap.ini file in the following manner, assuming that your web service is on server mdt01.local and the deployment share set in IIS as a Virtual Directory is PSDLTI001, also the access can't be anonymous, you need an account that have read access to the deployment share PSDLITI001:
[Default]
UserID=MDT_NAA
DeployRoot=https://mdt01.local/PSDLTI001
