### ISSUE TITLE
Litetouch iso boot is getting stuck, no progress

### ISSUE THREAD

**Issue by uday1kiran** [FriendsOfMDT/PSD#55]
There is no installer folder separately now as in step 9 in this link: https://www.brookspeppin.com/2020/06/26/how-to-setup-powershell-deployment-extension-for-mdt-with-https/

But, continued by selecting the file Install-PSD1 from main root/parent folder.

Then it prompted for wim file, but all the latest windows 10 enterprise/pro versions we download has ESD files, so converted them using this link: https://www.neeosearch.com/esd-wim-converter/

Then, I selected the install.wim file converted and tried to boot the generated litetouch iso file from a virtualbox VM. But it is frozen/stuck on the initial screen itself. No progress.

**Comment by GeoSimos** [comment]
I'm a bit confused about the scenario you're trying to work one, the ISO you created is done after having installed ADK, MDT and the PSD via the Install-PSD.ps1 script?

**Comment by GeoSimos** [comment]
Closing this issue as it is not relevant for the latest release and no response gotten from the requester.
Our policy states that stale issues will be closed after a month of inactivity.
