### ISSUE TITLE
Sysprep just a moment after Task Sequence

### ISSUE THREAD

**Issue by RaymondZaagsma** [FriendsOfMDT/PSD#56]
After installing Windows 10 21H2 via the PSDClient task sequence i give the machine a sysprep.exe /oobe /quiet /reboot. (with an whiteout  /mode:vm)
The virtual machine keeps hanging on just a moment no matter how long i wait.

Tried to remove the unattend xml in the pather folder (same result)

Tried the UnattendforAutopilotSysprep.xml of the website from Johan (same result)

Wim file i use is untouched and downloaded from my visualstudio portal (business edition)

**Comment by GeoSimos** [comment]
Could you provide more info regarding the scenario please? 
What is your target? To build an image for later deployment or deploy a vanilla image to new devices? 
SysPrep is used when you build an image for later mass deployment, it shouldn't be used for the deployment of either golden images (those that are built on ref devices and SysPrepped in the end of the process) or the vanilla ones provide by Microsoft.

**Comment by arwidmark** [comment]
This issue has been fixed in the latest release, basically a cleanup missing.

**Comment by Rukicc** [comment]
Can you explain how is planed to create Reference image for later deploy using this solution?
PSD Standard Client Task Sequence does not contain any preconfigured thinks about Sysprep, create WIM, etc.
