### ISSUE TITLE
How to do an in-place OS upgrade?

### ISSUE THREAD

**Issue by fataylor** [FriendsOfMDT/PSD#59]
Looking at the PSD templates, I don't see a template which does an OS Upgrade.  In the standard MDT templates, there was the ClientUpgrade.xml which utilized the UpgradeOS function in LTIApply.wsf.  How is this functionality accomplished in PSD(PSDApplyOS.ps1)?

Additionally, in my testing the PSDDeploymentShare.Get-PSDContent function has a return value of a string.  However, when control returns back to PSDStart.ps1, the return value is an array which is then attempted to be used as a string.  This is throwing errors.

**Comment by GeoSimos** [comment]
Hello, for the time being only the new computer scenario is provided/supported, the solution will be updated with more templates, when the functionality gets implemented.

**Comment by GeoSimos** [comment]
Please download the latest version as there were several fixes and enhancements in the meantime. Thank you!
