### ISSUE TITLE
After booting in WinPE and do Install phase (Apply Operating System) the computer is booting again on Network/USB disk instead of using UEFI Firmware 

### ISSUE THREAD

**Issue by Audigy35** [FriendsOfMDT/PSD#72]
this issue happens when deploying to physical machine this problem was in mdt 8443 and adk 1703 and was related to ltiapply script.wsf.
also i have another question how to to use mdt databae with the psd extension?
thank you for this great project.
avi

**Comment by arwidmark** [comment]
Hi, we did have this issue in an earlier version, on certain hardware models only, but it was fixed in version 0.2.2.8. Can you please upload the PSDApplyOS.log from the end of the WinPE phase (press F8 to prevent the machine from rebooting).

**Comment by Audigy35** [comment]
hi joan this issue happens on asus desktop model D700SA,D700TA,D700MA i need to some test about some of their business laptop to see if this problem occuer.

**Comment by arwidmark** [comment]
I can safely say we've never tested any of the ASUS desktops since businesses so rarely use them. If you can send me one of those devices (to Chicago), I'll be happy to spend some time and see what's going on. I would probably need to have the device for a week or so.

**Comment by Audigy35** [comment]
also another issue the applications step doesn't work when i have to to add the applications that i want to deploy in the task sequence editor.

**Comment by GeoSimos** [comment]
Hi @Audigy35,

This is a different issue from the one you reported, please let's keep each issue focused on that specific matter.
I would like to ask you to create another issue item and describe exactly what is it about. From what you reported I cannot discriminate if you refer to Application groups/bundles or single applications -which are working fine-.
Also please, as @arwidmark stated previously, check what version of the toolkit you have downloaded and if it is older than the current we have here, then it is better to download it and upgrade your PSD based deployment share(s). If your issue persist then please share your findings.

**Comment by Audigy35** [comment]
psd deployment share is version 0.2.2.8 which is the latest version when i select applications from the deployment wizard 
it shows the applications that i chosen but nothing is installed when the deployment reaches the install application stage.

**Comment by Audigy35** [comment]
the first issue is resolved my asus reboots to os after image is applied but when selleting application from the deployment wizard
single or mandatory doesn't work.

**Comment by GeoSimos** [comment]
> this issue is mentioned https://brookspeppin.com/2020/06/26/how-to-setup-powershell-deployment-extension-for-mdt-with-https/

This guide is very old in terms of the currently available version of PSD, even some of the steps are not valid anymore.

**Comment by GeoSimos** [comment]
Glad to know that your reported issue is fixed. I'm closing this issue item, please create a new one for the applications installation issue you're facing and include details and log files.

**Comment by Audigy35** [comment]
ok this my application.log:
<![LOG[Start-PSDLogging: Logging CMtrace logs to C:\MININT\SMSOSD\OSDLOGS\PSDApplications.log]LOG]!><time="09:16:56.832120" date="03-14-2023" component="PSDUtility.psm1:180" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDUtility.psm1">
<![LOG[PSDDeploymentShare.psm1: Reconnecting to the deployment share at https://GHOST-SERVER.labsrv.co.il/deploymentsharepsd.]LOG]!><time="09:16:56.988120" date="03-14-2023" component="PSDDeploymentShare.psm1:424" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDConnection: PowerShell variable global:psddsDeployRoot is now =  https://GHOST-SERVER.labsrv.co.il/deploymentsharepsd]LOG]!><time="09:16:57.066120" date="03-14-2023" component="PSDDeploymentShare.psm1:71" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDConnection: PowerShell variable global:psddsDeployUser is now = GHOST-SERVER.labsrv.co.il\administrator]LOG]!><time="09:16:57.066120" date="03-14-2023" component="PSDDeploymentShare.psm1:72" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[<Message containing password has been suppressed>]LOG]!><time="09:16:57.066120" date="03-14-2023" component="PSDDeploymentShare.psm1:73" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDContent: Download from Control to C:\MININT\Cache\Control took 00:00:00]LOG]!><time="09:16:57.098120" date="03-14-2023" component="PSDDeploymentShare.psm1:213" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDContent: Download from Templates to C:\MININT\Cache\Templates took 00:00:00]LOG]!><time="09:16:57.101120" date="03-14-2023" component="PSDDeploymentShare.psm1:213" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDProvider: PowerShell variable deployRoot is now = C:\MININT\Cache]LOG]!><time="09:16:57.103120" date="03-14-2023" component="PSDDeploymentShare.psm1:119" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDProvider: Set MDT Install_Dir to C:\MININT\Cache\ for MDT Provider.]LOG]!><time="09:16:57.114120" date="03-14-2023" component="PSDDeploymentShare.psm1:131" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDContent: Download from Tools\Modules to C:\MININT\Cache\Tools\Modules took 00:00:00]LOG]!><time="09:16:57.114120" date="03-14-2023" component="PSDDeploymentShare.psm1:213" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[Get-PSDProvider: Creating MDT provider drive DeploymentShare: at C:\MININT\Cache]LOG]!><time="09:16:57.145120" date="03-14-2023" component="PSDDeploymentShare.psm1:142" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[PSDApplications.ps1: Starting: PSDApplications.ps1 - Version 0.0.1]LOG]!><time="09:16:57.145120" date="03-14-2023" component="PSDApplications.ps1:45" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[PSDApplications.ps1: The task sequencer log is located at C:\MININT\SMSTSLog\SMSTS.LOG. For task sequence failures, please consult this log.]LOG]!><time="09:16:57.145120" date="03-14-2023" component="PSDApplications.ps1:46" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[PSDApplications.ps1: Main code]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDApplications.ps1:214" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[PSDApplications.ps1: Get tools]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDApplications.ps1:218" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[Get-PSDContent: Download from Tools\x64 to C:\MININT\Cache\Tools\x64 took 00:00:00]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDDeploymentShare.psm1:213" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDDeploymentShare.psm1">
<![LOG[PSDApplications.ps1: Checking for single application install step]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDApplications.ps1:225" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[PSDApplications.ps1: No Single Application install found. Continue with checking for dynamic applications]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDApplications.ps1:234" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[PSDApplications.ps1: Process applications]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDApplications.ps1:240" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[PSDApplications.ps1: No mandatory applications specified.]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDApplications.ps1:250" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">
<![LOG[PSDApplications.ps1: No applications specified.]LOG]!><time="09:16:57.301120" date="03-14-2023" component="PSDApplications.ps1:262" context="D700SA-002\Administrator" type="1" thread="5744" file="PSDApplications.ps1">

**Comment by GeoSimos** [comment]
Please create a new issue item and include the SMSTS.LOG along with the PSDApplications.log as file attachments. Also conceal any information you may not want to expose.
Thank you!

**Comment by Audigy35** [comment]
Here are my smsts.log and applications.log
