### ISSUE TITLE
Can't disable DeployReadiness

### ISSUE THREAD

**Issue by TheMrThx** [FriendsOfMDT/PSD#76]
Hi, in rules i set SkipDeployReadiness=YES but this didn't disable this step, how can I disable this?

**Comment by PowerShellCrack** [comment]
Have u tried adding it to the custom properties in the customsettings.ini? I believe that's is not a standard mdt property and will need to be called as custom. This also may need to be set as a standard property

**Comment by TheMrThx** [comment]
Yes, I tried add custom properties. My customsettings.ini looks like this:

[Settings]
Priority=Default
Properties=LogUserDomain,LogUserID,LogUserPassword,DriverPath,GenericDriverPath,FallBackDriverPath,PSDWizard,PSDWizardTheme,SkipDeployReadiness

[Default]
userexit=ADK2004DartFix.vbs
SkipDeployReadiness=NO
SkipComputerName=YES
SkipDomainMembership=YES
OSDComputerName=PC-Deployed
SkipAdminPassword=YES

SkipTaskSequence=YES
TaskSequenceID=0001
SkipProductKey=YES
SkipUserData=YES
SkipLocaleSelection=YES
SkipTimeZone=YES
SkipApplications=YES
SkipSummary=YES
SkipCapture=YES
SkipFinalSummary=YES
OSInstall=Y
PSDWizard=PSDWizardNew
PSDWizardTheme=Classic
_SMSTSORGNAME=ViaMonstra
_SMSTSPackageName=PC soon to be in Service
;LogUserDomain=Server
;LogUserID=AccountName
;LogUserPassword=P@ssw0rd
TimeZoneName=Central Standard Time
JoinWorkgroup=WORKGROUP
KeyboardLocale=0409:00000409
UILanguage=en-US
SystemLocale=en-US
SkipFinalSummary=NO
FinishAction=NONE
HideShell=NO
AdminPassword=Start123!

EventService=http://cloud-mdt.tt-tt.win:9800

**Comment by PowerShellCrack** [comment]
I noticed in your customsettings.ini, the second entry under [default] is SkipDeployReadiness=**NO**; This needs to be **YES**, but this may be a mistake on your part during the copy/paste. However, I did run this through my test environment, and it worked like it was supposed to:

Using your customsettings.ini configurations, when I set SkipDeployReadiness=**NO**; it would look like:
![image](https://user-images.githubusercontent.com/20599825/227723485-84726eff-c61c-41ac-8a0c-66a5c8837b67.png)

Where if I set SkipDeployReadiness=**YES**; it would look like this (notice no Deploy Readiness page is there?)
![image](https://user-images.githubusercontent.com/20599825/227723239-44f72800-fdc8-4a05-ad32-457a8ae19da4.png)

Are you seeing the same thing? If not, can you post screenshots? 

The only page I got was the Welcome screen. this can also be skipped by using the _SkipBDDWelcome=YES_ or _SkipPSDWelcome=YES_

Now I do admit that there should be a check to see if all pages are skipped, it should go directly into deployment without the need to click next. Even though the wizard can be skipped _SkipWizard=YES_ in the bootstrapp.ini; I will add that to my todo list.

**Comment by TheMrThx** [comment]
When I set SkipDeployReadiness=YES, it look like on second screenshots, is any way to disable need to click next on that page?

**Comment by PowerShellCrack** [comment]
Add SkipWizard=Yes to bootstrap.ini. This will disable the wizard completely. You will need to rebuild the boot wim after the change

**Comment by TheMrThx** [comment]
When I added SkipWizard=Yes to bootstrap.ini still have to click next to run deployment

**Comment by GeoSimos** [comment]
Have you rebuilt the boot image? Any changes in bootstrap.ini require a rebuild of it. And you have to use that image to boot and see the changes you applied.

**Comment by TheMrThx** [comment]
I rebuilt the boot image and use it to boot computer but still getting
screen witch two buttons “next” and “cancel”

**Comment by GeoSimos** [comment]
Let's wait for @PowerShellCrack to reply.

**Comment by PowerShellCrack** [comment]
I think this is a bug for the New UI. **I will add that to my list.** A workaround is to set _PSDWizard=**Native**_ and _SkipWizard=YES_ in the customsettings.ini. This will tell PSD to use the old UI, but since SkipWizard is set to YES, it will be skipped. 

I did test this, but can you confirm this is a workaround?

**Comment by TheMrThx** [comment]
I also thank you for the workaround, now after I set PSDWizard=Native and SkipWizard=YES everything working like expected.

**Comment by PowerShellCrack** [comment]
@GeoSimos documentation on the PSDWizard is now in pull request. [Detailed Guide for PSDWizard](https://github.com/FriendsOfMDT/PSD/pull/88). Hopefully this will be merged to be part of the repo

**Comment by GeoSimos** [comment]
> @GeoSimos documentation on the PSDWizard is now in pull request. [Detailed Guide for PSDWizard](https://github.com/FriendsOfMDT/PSD/pull/88). Hopefully this will be merged to be part of the repo

I have to engage @arwidmark and @DeploymentBunny  to merge it to the release development branch repository first. The public repository is a replica of it.
