### ISSUE TITLE
BranchCache guidance/advice

### ISSUE THREAD

**Issue by 3pichaxz0r** [FriendsOfMDT/PSD#79]
Looking for some general advice/guidance/tips on implementing branchcache with psd. I have the 2pint OSD toolkit addon working great but I seem to only pull about 60mb for a 1gb driver package in wim format and about 600mb for a 4.5gb os image (standalone wim). I have a windows server setup on my local network and I've tried:

- Export-BCCachePackage after staging the branchcache on the main PSD server and then importing the package on my local network's server. 
- cloning the PSD deployment share with syncthing to my local network's server and then using Publish-BCWebContent -Path "C:\PSD" -Recurse to publish the bc content
- Increased both publication cache and local cache to about 50% of the local network server's disk space (its a server just for branchcache testing)
- ensured that all default firewall rules are enabled for branchcache on my local network's server
- disabled bits limits for local network peers on local network server

I might be over estimating how much branchcache can be utilized here but I was expecting more than 600mb to be used for a 4.5gb os wim especially when the entire file is available on my local server. I've read through serveral 2pint KB articles on branchcache usage and several of Johan's blog articles on the subject to see if Im missing something but so far I can find anything.

Any advice or tips here are appreciated, I'm a bit of a noob to branchcache as you may be able to tell.

**Comment by 3pichaxz0r** [comment]
Small update, I changed my cache server to distributed bc mode and downloaded the os wim and driver package wim with BITS then tested a deployment using the same two wims. The driver package completely pulled from peer cache which was very satisfying to see but the OS wim didnt pull from peer cache at all, maybe because I imported the full os image rather than just a stand alone wim?

Im going to continue to mess around with things but any advice here is still very appreciated. I think a general guide on this subject would be good for other PSD users too.

**Comment by 3pichaxz0r** [comment]
Yep tested deploying a wim with only one index extracted from an iso install.wim and it is now pulling completely from peer cache

**Comment by Hammarskjold** [comment]
Yeah, so I am a little confused as what you are trying to do. Typically we peer without any servers, i.e. from client to client, but a server can peer to in distributed mode.

**Comment by 3pichaxz0r** [comment]
Sorry I was trying to figure out the best setup for remote locations where they might not be deploying multiple computers at the same time but still want to maintain up to date cache. I also hadn't really used branchcache before so a lot of it was a lack of understanding on how branchcache works

**Comment by 3pichaxz0r** [comment]
Sorry I was trying to figure out the best setup for remote locations where they might not be deploying multiple computers at the same time but still want to maintain up to date cache. I also hadn't really used branchcache before so a lot of it was a lack of understanding on how branchcache works
