### ISSUE TITLE
Stuck Checking for a valid network configuration

### ISSUE THREAD

**Issue by elyesusa** [FriendsOfMDT/PSD#85]
I have done a fresh install PSD MDT, and I have added a WDS for the PXE boot option; however the deployment hangs at the checking to validate a network connection even though the VM Test machine is getting a valid connection and PXE boot with no issues.
![Screenshot 2023-05-23 220120](https://github.com/FriendsOfMDT/PSD/assets/47729883/9839ab08-fff7-4f20-ab5a-a66cd61dbbce)
![Screenshot 2023-05-23 220038](https://github.com/FriendsOfMDT/PSD/assets/47729883/e5f778fc-0723-42b7-b22f-eb2ff5554c42)

**Comment by elyesusa** [comment]
I tired the ISO instead of PXE booting and I am experiencing the same errors

**Comment by GeoSimos** [comment]
Hi @elyesusa,

Please check by going to the cmd prompt (hit F8):

1. IPConfig (proper IP setup)
2. Resolution of the server's name
3. Test the connection to port 443 of your server

Thank you.

**Comment by elyesusa** [comment]
@GeoSimos Thank you for getting back to me, will go ahead test all of that, and get back to you with the results.

**Comment by 3pichaxz0r** [comment]
I had a similar issue at one point and it was resolved by reconfiguring the firewall Im using (pfsense) to use pure NAT. Just mentioning this if anyone is searching for a solution/possible cause.

**Comment by elyesusa** [comment]
Thank you all, was able to resolve the issue. Was using a hyper V for testing and somehow the virtual nic card won't allow me to reach out. Switched to prod and it is working as it should now.
