### ISSUE TITLE
BITS in WinPE

### ISSUE THREAD

**Issue by 3pichaxz0r** [FriendsOfMDT/PSD#90]
Looking for advice on how to call a bits transfer, specifically an upload, within WinPE. I assume there is some sort of trick to getting transfers working because when trying to just use the bits powershell module I get an error that it cant be loaded.

Thanks!

**Comment by GeoSimos** [comment]
I'm afraid you're asking the wrong question in the wrong place ;-)

**Comment by GeoSimos** [comment]
But maybe this will help you in your quest https://learn.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=windowsserver2019-ps.
