### ISSUE TITLE
Building boot image gets stuck on "Copying WIM to the deployment share"

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [FriendsOfMDT/PSD#91]
I've tried to build a test server using both the setup script as well as doing it manually - both times I seem to get stuck this portion:
![image](https://github.com/FriendsOfMDT/PSD/assets/76572698/0f703122-b0e5-448e-a6b0-1759b18598b9)
Both on Server 2022, latest MDT and ADKs. Building a WIM works on stock MDT on these boxes before I install PSD. Not sure what other info you'd need or if there are any logs for this process?

**Comment by BlueHairMinerBoy** [comment]
Just an update - if I disable ISO creation this process works fine so it seems to be getting stuck doing that. I can see the WIM get created in the Boot directory, just missing the ISO.

**Comment by GeoSimos** [comment]
Which version of ADK you have installed?

**Comment by Mase5150** [comment]
I am experiencing the same issue "Copying WIM to the deployment share". Using Windows Server 2019 with ADK for Windows 10, version 2004. Any suggestions?

**Comment by GeoSimos** [comment]
> I was previously having this is issue. What resolved it for me is when you set the execution policy in power shell, set it to bypass
> 
> set-executionpolicy bypass
> 
> hope this helps

Good tip to know!
Don't forget that the solution is PowerShell based, also the traditional MDT uses PowerShell for the UI actions, if you have a strict PowerShell execution policy, then you may want to set it to RemoteSigned because bypass is too relaxed.

**Comment by GeoSimos** [comment]
> Just an update - if I disable ISO creation this process works fine so it seems to be getting stuck doing that. I can see the WIM get created in the Boot directory, just missing the ISO.

The ISO is created by MDT, PSD is not involved in that part. As the execution policy of PowerShell may create such issues, the solution is to set it to RemoteSigned as Unrestricted or ByPass are too relaxed and risky.
More details here [about_Execution_Policies](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1).
