### ISSUE TITLE
Stuck on checking for a valid network configuration

### ISSUE THREAD

**Issue by kl0t3** [FriendsOfMDT/PSD#97]
We are trying to set this up within our VMware/ESXI environment . But we are getting the cmd prompt when launching the preboot Wim file at "checking for a valid network configuration". I see in a closed issue that they dint have this issue within a production server. Sadly our infrastructure works entirely on VMware and we need this work within VMware . Any solutions would be welcome.

**Comment by MacPaOnGit** [comment]
i had the same problem. in my case the problem was misconfigured DNS. i had an IP address assigned but i could not ping the PSD server by its fqdn. once i fixed that in pfsense the issue went away.

**Comment by pimpmyname2** [comment]
1. Missing network driver
2. Misconfigured DHCP server. Make sure the PSD server is pingable by fqdn as mentioned above :)

**Comment by 3pichaxz0r** [comment]
I assume the PSD server is hosted locally on the same subnet that the esxi vm is on that you are using to test the setup? If so I suggest using split dns to make sure the fqdn resolves as the local ip address for anything on the same network.

**Comment by kl0t3** [comment]
It was indeed DNS issue. We thought we dint need DNS when pointing directly to ip within Bootstrap.ini but that simply doesnt work. DNS server is required for this to work.

**Comment by kl0t3** [comment]
It was indeed DNS issue. We thought we dint need DNS when pointing directly to ip within Bootstrap.ini but that simply doesnt work. DNS server is required for this to work.
